### ISSUE TITLE
What does that thing do?

### ISSUE THREAD

**Issue by derrapf** [Ultimaker/cura-siemensnx-plugin#4]
I cannot find any description anywhere.
Description would be great what that thing does.
I found the menu in NX accidentally...

**Comment by Ghostkeeper** [comment]
I added a bit more information but I don't know the details either. I've never used Siemens NX myself, nor this plug-in. I hope someone can expand the readme a bit with some screenshots on usage or something.

**Comment by derrapf** [comment]
Ok. 
So what I found out, is that this plugin adds a menu in NX:
![image](https://user-images.githubusercontent.com/11745094/149819326-479f7200-2f43-4ba6-b26f-e0016bf0b335.png)
Once you hit it, NX will ask you which Body shall be transferred to CURA:
![image](https://user-images.githubusercontent.com/11745094/149819417-cd06901f-cb0e-49b8-b57b-142a368fb7ce.png)
Then you select the body and NX will open CURA and transfer that body to the CURA print bed.
That's so far what works for me. I guess there is no more behind it.
After installing that plugin, I thought there should be some extension or menu in CURA. But it's only the menu in NX.
So that's was somehow confusing.
Sorry - by the way - for the german screenshots. I only have those.
BR 
Ralf

**Comment by Ghostkeeper** [comment]
Indeed, no changes are made to Cura itself. It seems that all that this plug-in does is [install some files to NX's directory](https://github.com/Ultimaker/cura-siemensnx-plugin/blob/f222360186cded4eeb379f2bccee1fcfa25cbaa9/Installer.py#L31)

I could ask around if someone can make better instructions. It seems that I'm the only one monitoring this right now.

**Comment by Ghostkeeper** [comment]
I found this article: https://ultimaker.com/learn/recap-siemens-plm-connection-2017

The screenshots there are a bit too poor to use, but it at least allows for a bit of a better write-up combined with your experiences.

**Comment by derrapf** [comment]
Yes, those are nearly the same screenshots as I made. But in english.
I experienced another issue (which is not a big issue):
It is not possible to select a body in an assembly. The component has to be set as "active part" before.

**Comment by derrapf** [comment]
>Indeed, no changes are made to Cura itself. 
Yes. I also tried to investigate the Code.
It's just some menus that are installed in UGII_USER_DIR and a short VB Script. CURA is started from VB
